//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Hutech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public int ID { get; set; }
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> LoaiSach { get; set; }
        public string NamXB { get; set; }
        public Nullable<int> NXB { get; set; }
        public Nullable<int> TacGia { get; set; }
        public Nullable<int> ViTri { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> Muon { get; set; }
        public string NgonNgu { get; set; }
        public Nullable<System.DateTime> TimeCreate { get; set; }
        public Nullable<System.DateTime> TimeUpdate { get; set; }
        public string ImagePath { get; set; }
    
        public virtual LoaiSach LoaiSach1 { get; set; }
        public virtual NXB NXB1 { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual TacGia TacGia1 { get; set; }
        public virtual ViTri ViTri1 { get; set; }
    }
}
